// AUTO-GENERATED by demo-video skill — GAP MODE (TTS narration, 1.0x playback)
// Story: the prove engine. Every number and terminal line here is real and verified
// against prove/proofs/*.json, bench/, and the on-chain deployments (2026-10-02).
export const FPS = 30;
export const W = 1920;
export const H = 1080;

export const PACING_MODE = "gap" as const;
export const PLAYBACK_RATE = 1.0;

// --- THEME: Quorum brand (green on near-black) ---
export const COLORS = {
  bg: "#080c09",
  bgCard: "rgba(15,30,18,0.62)",
  bgCardStrong: "rgba(12,24,15,0.92)",
  accent: "#3fb950",
  accentDim: "#166534",
  accentBright: "#5ddb70",
  accentGlow: "rgba(63,185,80,0.15)",
  white: "#eef5ef",
  offWhite: "#a8b8ac",
  muted: "#5a6e5e",
  border: "rgba(63,185,80,0.22)",
  borderStrong: "rgba(63,185,80,0.4)",
  red: "#f85149",
  amber: "#d29922",
  cyan: "#22d3ee",
  terminalBg: "#0a120c",
};

export const TERMINAL = {
  bg: "#0a120c",
  text: "#c9d9cd",
  green: "#3fb950",
  yellow: "#d29922",
  red: "#f85149",
  blue: "#58a6ff",
  purple: "#bc8cff",
  prompt: "#5a6e5e",
};

export const ORBS = [
  { baseX: 250, baseY: 210, size: 480, color: COLORS.accent, blur: 120, opacity: 0.12, speed: 0.006 },
  { baseX: 1560, baseY: 780, size: 420, color: COLORS.accentDim, blur: 110, opacity: 0.11, speed: 0.005 },
  { baseX: 960, baseY: 520, size: 560, color: "#0e7490", blur: 140, opacity: 0.08, speed: 0.008 },
  { baseX: 1690, baseY: 170, size: 380, color: COLORS.cyan, blur: 100, opacity: 0.06, speed: 0.007 },
  { baseX: 180, baseY: 840, size: 320, color: COLORS.accent, blur: 100, opacity: 0.06, speed: 0.009 },
];

// --- SCENE ORDER: must mirror MainVideo TransitionSeries order exactly ---
export const SCENE_ORDER = ["hook", "contrast", "terminal", "numbers", "onchain", "close"] as const;
export type SceneKey = (typeof SCENE_ORDER)[number];

// --- AUDIO DURATIONS: actual Brian (edge-tts en-US-BrianNeural) length from ffprobe ---
export const AUDIO_DURATIONS: Record<SceneKey, number> = {
  hook: Math.round(8.447 * FPS), // 253
  contrast: Math.round(9.796 * FPS), // 294
  terminal: Math.round(13.481 * FPS), // 404
  numbers: Math.round(10.953 * FPS), // 329
  onchain: Math.round(14.274 * FPS), // 428
  close: Math.round(4.267 * FPS), // 128
};

// --- SCENE GAP: silent breathing room after each clip ---
export const SCENE_GAP = Math.round(1.5 * FPS); // 45 frames

export const SCENE_DURATIONS: Record<SceneKey, number> = {
  hook: AUDIO_DURATIONS.hook + SCENE_GAP,
  contrast: AUDIO_DURATIONS.contrast + SCENE_GAP,
  terminal: AUDIO_DURATIONS.terminal + SCENE_GAP,
  numbers: AUDIO_DURATIONS.numbers + SCENE_GAP,
  onchain: AUDIO_DURATIONS.onchain + SCENE_GAP,
  close: AUDIO_DURATIONS.close + SCENE_GAP,
};

export const CROSSFADE = 15;

export const TOTAL_FRAMES =
  Object.values(SCENE_DURATIONS).reduce((a, b) => a + b, 0) - CROSSFADE * (SCENE_ORDER.length - 1);

export const AUDIO_FILES: Record<SceneKey, string> = {
  hook: "audio/hook.mp3",
  contrast: "audio/contrast.mp3",
  terminal: "audio/terminal.mp3",
  numbers: "audio/numbers.mp3",
  onchain: "audio/onchain.mp3",
  close: "audio/close.mp3",
};

// --- SUBTITLES: scene-local frame numbers, GAP MODE (Math.round(whisper_seconds * FPS)) ---
// Display text is the real script; timing is Whisper on the actual Brian audio.
type Sub = { text: string; start: number; end: number };
export const SUBTITLES: Record<SceneKey, Sub[]> = {
  hook: [
    { text: "Most security findings are a confident guess.", start: 0, end: 82 },
    { text: "Quorum publishes only the ones it can prove —", start: 88, end: 152 },
    { text: "by running the exploit until the money actually moves.", start: 152, end: 253 },
  ],
  contrast: [
    { text: "A scanner flags a line. A report asserts impact.", start: 0, end: 100 },
    { text: "Quorum writes a Foundry exploit on a mainnet fork,", start: 111, end: 190 },
    { text: "and keeps the finding only if the attacker's balance goes up.", start: 195, end: 294 },
  ],
  terminal: [
    { text: "It takes a real 2026 hack, finds the entry on-chain, drains it on a fork,", start: 0, end: 207 },
    { text: "712 USDC. Moved.", start: 207, end: 258 },
    { text: "Four hacks reproduced this way — one with the answer withheld from the model.", start: 258, end: 404 },
  ],
  numbers: [
    { text: "It also publishes how often it is wrong.", start: 0, end: 88 },
    { text: "Recall on 143 known-bug contracts, measured over eleven runs.", start: 90, end: 220 },
    { text: "The one row where Slither still beats it stays on the page.", start: 233, end: 329 },
  ],
  onchain: [
    { text: "A proof is not a PDF.", start: 0, end: 48 },
    { text: "Each one settles as a paid on-chain claim.", start: 61, end: 128 },
    { text: "The registry burns the fee and records the digest in a single transaction —", start: 137, end: 252 },
    { text: "so a record cannot exist without its own cost.", start: 263, end: 342 },
    { text: "Live on Robinhood Chain and Arbitrum One.", start: 350, end: 428 },
  ],
  close: [
    { text: "Quorum. Prove it, or drop it.", start: 0, end: 62 },
    { text: "Live at runquorum.site.", start: 67, end: 128 },
  ],
};

// =============================================================
// CONTENT (real, verified) — scenes read from here, never hardcode
// =============================================================

// Hook: the four wei-exact proofs. Source: prove/proofs/*.json, bench/STREAM.md.
export const PROOFS = [
  { name: "Unistreet", amount: "+0.0072 WETH", chain: "ethereum" },
  { name: "Sandbox", amount: "+1,000,000 SAND", chain: "base" },
  { name: "Squid", amount: "+712 USDC", chain: "ethereum" },
  { name: "GaslessReservoir", amount: "+0.836 WETH", chain: "polygon·blind" },
];

// Terminal: the real forge output for the Squid (NewMarketTrading) proof.
// Verbatim from prove/proofs/NewMarketTrading.json forge_tail (block 25170513).
// 0xA0b8…eB48 is USDC; 712632808 units / 1e6 = 712.63 USDC.
export const TERMINAL_CMD = "python prove/tool.py prove ethereum SquidRouterModule --block 25170513";
export const TERMINAL_LINES: { text: string; color: keyof typeof TERMINAL; bold?: boolean }[] = [
  { text: "Ran 1 test for test/Exploit.t.sol:ExploitTest", color: "text" },
  { text: "[PASS] test_exploit() (gas: 7815566)", color: "green" },
  { text: "Logs:", color: "prompt" },
  { text: "  [before] attacker 0xA0b8…eB48  0", color: "text" },
  { text: "  [after ] attacker 0xA0b8…eB48  712632808", color: "text" },
  { text: "  [PROOF] attacker gained 0xA0b8…eB48 712632808", color: "green", bold: true },
  { text: "Suite result: ok. 1 passed; 0 failed; 0 skipped", color: "text" },
];
export const TERMINAL_CALLOUT = "+712.63 USDC drained from a real victim Safe";

// Numbers: recall across eleven benchmark runs. Source: docs/index.html chart + bench/BENCHMARK.md.
export const RECALL_SERIES = [1, 23, 31, 40, 62, 63, 63, 62, 62, 63, 64];
export const RECALL_HEADLINE = "64%";
export const RECALL_SUB = "recall · 143 known-bug contracts · 11 runs";
// Honesty row: reentrancy 72% vs Slither 62% (bench/README.md:143); Slither wins access-control.
export const COMPARE_ROWS = [
  { risk: "reentrancy", quorum: "72%", slither: "62%", win: "quorum" as const },
  { risk: "access-control", quorum: "lower", slither: "higher", win: "slither" as const },
];

// OnChain: the claim layer, live on two chains. Source: CLAUDE.md Verified Facts (2026-10-02).
export const CLAIM_FEE = "100,000 QUORUM";
export const RH_TX = "0x2f22250d…ffc3d";
export const CHAINS = [
  { name: "Robinhood Chain", id: "chain 4663 · Arbitrum Orbit", addr: "0xDeA0…3Ea3" },
  { name: "Arbitrum One", id: "chain 42161", addr: "0xd2ca…2774" },
];

// Close
export const CLOSE_URL = "runquorum.site";
export const CLOSE_EVENT = "Arbitrum Open House · Singapore";
